language: php
sudo: false

matrix:
    include:
        - php: 7.0
        - php: 7.1
        - php: nightly
        - php: hhvm-stable
          sudo: required
          dist: trusty

before_install:
    - if [[ $TRAVIS_PHP_VERSION = hhvm* ]]; then echo hhvm.php7.all=1 >> /etc/hhvm/php.ini; fi
    - if [[ $TRAVIS_PHP_VERSION = hhvm* ]]; then echo hhvm.php7.scalar_types=0 >> /etc/hhvm/php.ini; fi # https://github.com/facebook/hhvm/issues/7198

before_script:
    - composer config disable-tls true
    - composer config secure-http false
    - composer install --prefer-source

script: vendor/bin/phpunit

notifications:
    email: false
